Parameters:
  myVPC:
      Description: VPC used to deploy our resources below
      Type: AWS::EC2::VPC::Id
  PublicSubnet:
      Description: Subnet to be used for our Web Server
      Type: AWS::EC2::Subnet::Id
  ServerInstanceAMI:
      Description: AMI to use for our base image
      Type: String
  ServerInstanceType:
    Description: Intance type
    Default: t2.micro
    Type: String
Resources:
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to our test host
        VpcId:
          Ref: myVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  WebServerInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref ServerInstanceType
      ImageId: !Ref ServerInstanceAMI
      KeyName: ansible-key
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: WebAccessSecurityGroup
          SubnetId: 
            Ref: PublicSubnet
      Tags: 
        - Key: Project 
          Value: udacity
  # EC2KeyPair:
  #   Type: AWS::EC2::KeyPair
  #   Properties: 
  #     KeyName: ansible-key
  #     # PublicKeyMaterial:  
  #     Tags: 
  #       - Key: Project 
  #         Value: udacity

